### ISSUE TITLE
about the paper code?

### ISSUE THREAD

**Issue by guoyage** [Khrylx/AgentFormer#1]
Hi, when you will publish the paper code.

**Comment by Khrylx** [comment]
Hi, we plan to release the code after publication in proceedings.

**Comment by darshb34** [comment]
Hello @Khrylx 
Great work! Loved the paper <3. 

May I know  what is the tentative target date for code release?

Thank you for the response.

**Comment by Khrylx** [comment]
Hi, we are actively cleaning the code and will release it before the camera-ready ddl of ICCV 2021.

**Comment by Khrylx** [comment]
Code is released!
