### ISSUE TITLE
data processing

### ISSUE THREAD

**Issue by JaneFo** [Khrylx/AgentFormer#10]
Hello, this is an excellent job, but I don't understand one question, I hope you can answer them.
The first is why the eth/ UCY data processing needs to divid the scale: like "found_data = past_data[past_data[:, 1] == identity].squeeze()[[self.xind, self.zind]] / self.past_traj_scale". The self.past_traj_scale=2, but in Trajectron++, the dataset is not divide the scale.

Looking forward to your reply.

**Comment by Khrylx** [comment]
Hi,

Scaling the trajectory into a smaller range can improve the network's performance since the input is now more normalized, which is also what we observed in the experiments. You can also try to set traj_scale to 1 in the config file.

**Comment by JaneFo** [comment]
您好，我是付峥，来信我已收到，我会在查收邮件之后给您回复。
