### ISSUE TITLE
Questions about Visualization

### ISSUE THREAD

**Issue by PhehJingJie** [Khrylx/AgentFormer#11]
Hi @Khrylx ,

Thank you for your work, it is really impressive. 

I am wondering if you have the visualisation script for these visualisation that you did.
<img width="991" alt="Screenshot 2021-11-12 at 10 38 27 PM" src="https://user-images.githubusercontent.com/50895766/141484242-269c5094-7d00-41f1-ab50-6c5fdf8d45bb.png">
<img width="1020" alt="Screenshot 2021-11-12 at 10 38 44 PM" src="https://user-images.githubusercontent.com/50895766/141484296-5ee581f4-8d77-4c1f-b9a6-10b25aa94ed1.png">

**Comment by Khrylx** [comment]
Hi,

Code for visualization has not been cleaned yet and may not be compatible with the current repo. The attention is visualized using the attention weight matrix of the first Transformer layer.

**Comment by mpourkeshavarz** [comment]
@jjbecomespheh 
Hi,
did you try any visualization?

**Comment by krishnakanthnakka** [comment]
Would it be possible for authors to share the visualization script at least for Figure (a) part?

Thanks in advance

**Comment by zehranrgi** [comment]
any update? @Khrylx
