### ISSUE TITLE
some puzzles about the math formulas in the CVAE Future Decoder part

### ISSUE THREAD

**Issue by ultimatedigiman** [Khrylx/AgentFormer#12]
As you described in section 3.2 of the paper:
<img width="550" alt="image" src="https://user-images.githubusercontent.com/67790229/143509648-34d8f9a4-6ab7-447e-a7fb-d347f6ef7053.png">
I can understand the purpose of the MSE term **||Y-\hat Y||^2** is to push the real value **Y** and the mean of the Guassian **\hat Y** as close as possible,because the Gaussian distribution has the maximum probability value at the mean value.
But where did the weighting factor **1/(2beta)** come from? Why dividing the variance by **beta** leads to this weighting factor?

**Comment by Khrylx** [comment]
This is a typo. It should be 0.5\beta before the MSE term to make it an actual weighting factor. Nice catch

**Comment by ultimatedigiman** [comment]
> This is a typo. It should be 0.5\beta before the MSE term to make it an actual weighting factor. Nice catch

Did you mean the actual conditional likelihood **P(Y|Z,X,I)** is **N(\hat Y,I)** which is as same as the original CVAE?

**Comment by ultimatedigiman** [comment]
> This is a typo. It should be 0.5\beta before the MSE term to make it an actual weighting factor. Nice catch

Hi,
Could you please figure out why dividing the Guassian standard deviation **I** by **beta** leads to the weighting factor **1/(2beta)**?
<img width="206" alt="image" src="https://user-images.githubusercontent.com/67790229/143732572-54ad49ef-6a39-4167-bae0-96a4a2a89989.png">
How can I derive the weighting factor **1/(2beta)** from the Guassian standard deviation **I/beta**?

**Comment by Khrylx** [comment]
Hi,

i already said that it is a typo, it should be 0.5beta ||Y-\hat{Y}||^2.

**Comment by ultimatedigiman** [comment]
> Hi,
> 
> i already said that it is a typo, it should be 0.5beta ||Y-\hat{Y}||^2.

Thanks for the quick reply!
I'm afraid I mistaken the **\beta** in your last reply as dividing by **beta**.
But I still don't understand why dividing the Guassian standard deviation **I** by **beta** leads to the weighting factor **0.5beta**?
Is there a derivation process?
<img width="206" alt="image" src="https://user-images.githubusercontent.com/67790229/143734159-ef6b690a-e004-4694-a07c-aa2d48e08e07.png">

**Comment by Khrylx** [comment]
Hello, sorry for the late reply.

I think if you take the log probability of the GT trajectory Y under the normal distribution, you will get the MSE loss.
