### ISSUE TITLE
ADE/FDE Future mask Loss

### ISSUE THREAD

**Issue by linaashaji** [Khrylx/AgentFormer#15]
Hello, 
I have seen that you are using a mask on the MSE loss to not take into consideration the padded agents, which is good.
However, why aren't you applying the same on the ADE and FDE metrics?

**Comment by Khrylx** [comment]
Hi,

Actually, when I obtain future sequences I always make sure that the future frames all exist. So there is no need to use the masks as they will be all 1.
https://github.com/Khrylx/AgentFormer/blob/main/cfg/eth_ucy/eth/eth_agentformer_pre.yml#L12-L15
