### ISSUE TITLE
Reg. distance between adjacent grid points in semantic maps for nuscenes

### ISSUE THREAD

**Issue by hrshl212** [Khrylx/AgentFormer#19]
Hi, congrats on the excellent work. I was going through your code and found that while converting the position of the agent in the image to pixel position you are multiplying it with a scale = 3. That should mean that the distance between adjacent pixels is 1/3 m as opposed to 3 m mentioned in the paper. Please let me know if I am interpreting anything wrong.

**Comment by Khrylx** [comment]
Nice catch! I think you are right. We were following Trajectron++'s map processing procedure, so we assumed 3m as mentioned in their paper.
