### ISSUE TITLE
Question about paper result

### ISSUE THREAD

**Issue by minano430** [Khrylx/AgentFormer#2]
Thanks for sharing this great work!!
I have a few question about this paper, how did you get the fde result of nuScene?
I search the leader board on nuScenes and the result of yours out performed those method. (Really differ greatly)
So just want to know about how you calculate the result.

**Comment by Khrylx** [comment]
Hi,

I think you might be comparing our FDE_5 (3.14) and FDE_10 (2.48) with the FDE_1 on the official nuScenes leaderboard. The leaderboard only reports FDE_1, which is the one sample FDE and is much higher than FDE_5 and FDE_10. That said, our FDE_1 is 6.45, which is still the best among all the methods. To answer your question, our FDE is computed using this function: https://github.com/Khrylx/AgentFormer/blob/main/eval.py#L22-L30
You can also try to reproduce the numbers by running:
```
python test.py --cfg nuscenes_1sample_agentformer --gpu 0
```
