### ISSUE TITLE
Nuscene Dataset Question

### ISSUE THREAD

**Issue by zyaocoder** [Khrylx/AgentFormer#4]
Hi,

Thanks for your wonderful work on this paper, you guys did a good job!

I have a question: did you use the training set obtained from all cameras on the Nuscenes dataset?

Thanks ahead for your help!

**Comment by Khrylx** [comment]
Hi, thank you for your kind words.

We are only using a subset of data as specified by the nuScenes prediction challenge (https://github.com/nutonomy/nuscenes-devkit#prediction-challenge), and we only use bird-eye view map information and past trajectories.
You check out the details in this script: https://github.com/Khrylx/AgentFormer/blob/main/data/process_nuscenes.py

**Comment by Mirorrn** [comment]
Hello,

so we only need the meta data and the maps data? Sweeps and samples are therefore not releveant and do not need to be downloaded?

Many greetings,
Mirorn

**Comment by Khrylx** [comment]
Hi,

I think you would still need to Download the original nuScenens dataset and then download the map expansion. I haven't tried to directly use meta data and map data, but I suspect that won't work.

**Comment by sudarshanregmi** [comment]
Awesome work! 

Sorry for bothering you. For bird-eye view map information and past trajectories, do I need to download the whole dataset (~300 GBs) ? Or do I need to just download keyframes? I see, there are 10 parts of dataset. From the nuScenes repository, I see that this is the structure we need. 

![image](https://user-images.githubusercontent.com/19612493/131545579-399d9ee3-8c42-4482-bf1a-c46a746a3d4c.png)
 
 Could you please give the pointers? 

 
![image](https://user-images.githubusercontent.com/19612493/131545817-8345ddae-dbdf-4a47-bef3-75788a1dba13.png)

**Comment by Khrylx** [comment]
Hi @sudarshanregmi,

I think you only need to download the samples, i.e., keyframe data. Please let me know if this works for you. Thanks!

**Comment by sudarshanregmi** [comment]
Thank you very much for the reply! 

Do I need everything inside this folder? 

![image](https://user-images.githubusercontent.com/19612493/131603506-d23e3cbd-6398-4740-b34f-48bf753a0839.png)

**Comment by Khrylx** [comment]
I think you mainly need the annotation. Could you try running https://github.com/Khrylx/AgentFormer/blob/main/data/process_nuscenes.py? If it doesn't work, then maybe you need to download those.

**Comment by sudarshanregmi** [comment]
Thank you very much. I'll let you know if I get it right!

**Comment by dylantzx** [comment]
Hi, I just tried and am able to successfully run `process_nuscenes.py` and `test.py` on the nuscenes dataset.

For me, I downloaded the Metadata, Map Expansion, and Keyframe blobs for all 10 parts and merged the samples folders of all 10 parts. It looks something like this now:
```
.
├── maps
│   ├── basemap
│   ├── expansion
│   └── prediction
├── samples
│   ├── CAM_BACK
│   ├── CAM_BACK_LEFT
│   ├── CAM_BACK_RIGHT
│   ├── CAM_FRONT
│   ├── CAM_FRONT_LEFT
│   ├── CAM_FRONT_RIGHT
│   ├── LIDAR_TOP
│   ├── RADAR_BACK_LEFT
│   ├── RADAR_BACK_RIGHT
│   ├── RADAR_FRONT
│   ├── RADAR_FRONT_LEFT
│   └── RADAR_FRONT_RIGHT
└── v1.0-trainval
```
Each folder in samples consists of ~34,149 files. Total space for everything was ~60GB.

**Comment by MZ82020** [comment]
@dylantzx Hello, Hope you are fine! 

Can you share with me the complete folder please? I have tried many times but the script does not work ..

Thanks !

**Comment by dylantzx** [comment]
@MZ82020 Hello, if you still need it, perhaps you can provide your email and I'll send the zipped processed files to you?

**Comment by Khrylx** [comment]
Closing this issue for now.

**Comment by mpourkeshavarz** [comment]
@dylantzx Thanks for the sharing,
Would you please share the number of samples in each split after loading by the dataloader? if you check your log.txt, you can see some prints like below:

> loading sequence scene-1073 ...
> total num samples: 3320
> ------------------------------ done --------------------------------

**Comment by Carrotsniper** [comment]
> @MZ82020 Hello, if you still need it, perhaps you can provide your email and I'll send the zipped processed files to you?

Hi, can you share the processed files to me as well?

**Comment by zehranrgi** [comment]
Hi, I am using mini nuscene dataset. Not sure how to correct this error?  @Khrylx  @dylantzx 
 
  File "data/process_nuscenes.py", line 83, in <module>
    scene_token = nuscenes.field2token('scene', 'name', scene_name)[0]
IndexError: list index out of range

I printed line 83 and : scene name scene-0301. Mini scene json file has not this scene name and token.

**Comment by Marcelaine** [comment]
@zehranrgi Hi, I also have this problem when using mini nuscene dataset. Have you fixed it?

**Comment by zehranrgi** [comment]
> @zehranrgi Hi, I also have this problem when using mini nuscene dataset. Have you fixed it?

Hi, I couldn't remember how to solve but I was able to run this model, yes. 
I suppose, you need to check the organization of your dataset. and, as a default, it doesn't take mini dataset at that file. you need to change it, too.
